
import MyContext  from "@/context/Context";
import "./globals.css";



export const metadata = {
  title: "Next.js",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body suppressHydrationWarning>

        <MyContext>
        {children}

        </MyContext>
        
      </body>
    </html>
  );
}
